import React from "react";
import Head from "next/head";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import TopHeader from "@/components/TopHeader";
import Header from "@/components/Header";
import Slider from "react-slick";
import HeroBanner from "@/components/HeroBanner";
import Footer from "@/components/Footer";
import BusinessHeader from "@/components/BusinessHeader";
import ServiceCard from "@/components/ServiceCard";

export default function business() {
  var settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false,
    autoplay: true,
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>
      <main>
        <TopHeader />
        <BusinessHeader />
        <Slider {...settings}>
          <HeroBanner
            header="Dedicated Internet"
            description=" Strong and dedicated leased line connectivity for your company"
            image="https://history-computer.com/wp-content/uploads/2022/08/shutterstock_1684873624-scaled.jpg"
            btnText="Explore"
          />
          <HeroBanner
            header="Full-stack Solutions"
            description="Best-in-class solutions engineered by professional architects "
            image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTeQff_2Nb5tz1OMG6T4GlLRHGNVLFf28Yeg&usqp=CAU"
            btnText="TeleCloud"
          />
          {/* <HeroBanner
            header="Get your prepaid sim"
            description=" Enjoy doorstep KYC, paperless process, and quick activation"
            image="https://mir-s3-cdn-cf.behance.net/project_modules/disp/7a1c7e9995317.560ddb5268ce3.png"
            btnText="BUY SIM"
          /> */}
        </Slider>
        <h1 className=" bg-[#fafafa] text-center text-2xl font-semibold pt-5 pb-3">
          Products for all your business needs
        </h1>
        <section className=" flex flex-wrap justify-center bg-[#fafafa] mb-4">
          <ServiceCard />
          <ServiceCard />
          <ServiceCard />
          <ServiceCard />
          <ServiceCard />
          <ServiceCard />
        </section>

        <Footer />
      </main>
    </>
  );
}
