import React, { useEffect } from "react";
import Header from "@/components/Header";
import HeroBanner from "@/components/HeroBanner";
import TopHeader from "@/components/TopHeader";
import Head from "next/head";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";
import ArticleCard from "@/components/ArticleCard";
import Footer from "@/components/Footer";
import GoogleTranslate from "@/components/GoogleTranslate";
export default function Home() {
  var settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false,
    autoplay: true,
  };

  var settingss = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 3,
    slidesToScroll: 3,
    arrows: false,
    autoplay: true,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 3,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 900,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
        },
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
      // You can unslick at a given breakpoint now by adding:
      // settings: "unslick"
      // instead of a settings object
    ],
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>

      <div className=" ">
        <TopHeader />
        <Header />
        <Slider {...settings}>
          <HeroBanner
            header="Get your prepaid sim"
            description=" Enjoy doorstep KYC, paperless process, and quick activation"
            image="https://mir-s3-cdn-cf.behance.net/project_modules/disp/7a1c7e9995317.560ddb5268ce3.png"
            btnText="BUY SIM"
          />
          <HeroBanner
            header="Pay safe, Earn Reward"
            description=" Send money, make payments & get loans do all this and more with ease on Airtel Payments Bank."
            image="https://mobilemoney.et/img/intro-mobile.png"
            btnText="DOWNLOAD APP"
          />
          {/* <HeroBanner
            header="Get your prepaid sim"
            description=" Enjoy doorstep KYC, paperless process, and quick activation"
            image="https://mir-s3-cdn-cf.behance.net/project_modules/disp/7a1c7e9995317.560ddb5268ce3.png"
            btnText="BUY SIM"
          /> */}
        </Slider>
        <section className=" bg-[#f7f7fa]">
          <h1 className=" text-center font-semibold text-xl py-5">
            Product and Services
          </h1>
          <section className=" mx-12">
            <Slider {...settingss}>
              <ArticleCard
                image={
                  "https://ethio.news/wp-content/uploads/2018/09/Untitled-design-7-1-768x402.png"
                }
                tagline="PACKAGE"
                header="No expiry data Package"
                description=" we offer no expiry data packages, to get 10% off pay with telebirr"
                buttonText="Read More"
              />

              <ArticleCard
                image={"https://pbs.twimg.com/media/EvtFB5tXAAEt2Fa.jpg"}
                tagline="App"
                header="Download My Ethiotel App"
                description=" we offer no expiry data packages, to get 10% off pay with telebirr"
                buttonText="Download App"
              />
              <ArticleCard
                image={
                  "https://ocdn.eu/pulscms-transforms/1/6Q8ktkpTURBXy82ODA0MzQzNGRkN2ViOGIxZDIzMDE3MDUxZDQwYzZkZi5qcGeSlQMAAs0C280Bm5MFzQKAzQFA"
                }
                tagline="Sim"
                header="Get your 5G Simcard"
                description=" we offer no expiry data packages, to get 10% off pay with telebirr"
                buttonText="Read More"
              />
            </Slider>
          </section>

          {/* <div className=" flex justify-around flex-wrap">
            <ArticleCard />
            <ArticleCard />
            <ArticleCard />
          </div> */}
        </section>
        <Footer />
        {/* <GoogleTranslate /> */}
      </div>
    </>
  );
}
